# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(577, 398)
        Dialog.setStyleSheet("background-color: rgb(155, 232, 232);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 20, 141, 31))
        self.label.setObjectName("label")
        self.valor1 = QtWidgets.QTextEdit(Dialog)
        self.valor1.setGeometry(QtCore.QRect(80, 80, 131, 41))
        self.valor1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.valor1.setObjectName("valor1")
        self.valor2 = QtWidgets.QTextEdit(Dialog)
        self.valor2.setGeometry(QtCore.QRect(270, 80, 131, 41))
        self.valor2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.valor2.setObjectName("valor2")
        self.resultado = QtWidgets.QLabel(Dialog)
        self.resultado.setGeometry(QtCore.QRect(460, 80, 61, 31))
        self.resultado.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.resultado.setObjectName("resultado")
        self.bsuma = QtWidgets.QPushButton(Dialog)
        self.bsuma.setGeometry(QtCore.QRect(60, 170, 80, 25))
        self.bsuma.setObjectName("bsuma")
        self.bresta = QtWidgets.QPushButton(Dialog)
        self.bresta.setGeometry(QtCore.QRect(60, 210, 80, 25))
        self.bresta.setObjectName("bresta")
        self.bmultiplicar = QtWidgets.QPushButton(Dialog)
        self.bmultiplicar.setGeometry(QtCore.QRect(60, 250, 80, 25))
        self.bmultiplicar.setObjectName("bmultiplicar")
        self.bcociente = QtWidgets.QPushButton(Dialog)
        self.bcociente.setGeometry(QtCore.QRect(60, 290, 80, 25))
        self.bcociente.setObjectName("bcociente")
        self.btangente = QtWidgets.QPushButton(Dialog)
        self.btangente.setGeometry(QtCore.QRect(180, 290, 80, 25))
        self.btangente.setObjectName("btangente")
        self.bcoseno = QtWidgets.QPushButton(Dialog)
        self.bcoseno.setGeometry(QtCore.QRect(180, 250, 80, 25))
        self.bcoseno.setObjectName("bcoseno")
        self.bresiduo = QtWidgets.QPushButton(Dialog)
        self.bresiduo.setGeometry(QtCore.QRect(180, 170, 80, 25))
        self.bresiduo.setObjectName("bresiduo")
        self.bseno = QtWidgets.QPushButton(Dialog)
        self.bseno.setGeometry(QtCore.QRect(180, 210, 80, 25))
        self.bseno.setObjectName("bseno")
        self.bcosecante = QtWidgets.QPushButton(Dialog)
        self.bcosecante.setGeometry(QtCore.QRect(300, 250, 80, 25))
        self.bcosecante.setObjectName("bcosecante")
        self.bcotangente = QtWidgets.QPushButton(Dialog)
        self.bcotangente.setGeometry(QtCore.QRect(300, 170, 80, 25))
        self.bcotangente.setObjectName("bcotangente")
        self.bsecante = QtWidgets.QPushButton(Dialog)
        self.bsecante.setGeometry(QtCore.QRect(300, 210, 80, 25))
        self.bsecante.setObjectName("bsecante")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 550, 241, 41))
        #self.label_4.setStyleSheet("border-image: url(:/cct/logo ECCI.jpg);")
        
        self.label_4.setStyleSheet("border-image: url(/home/juliapaez1227/Downloads/logo_ecci.png)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">calculadora</p></body></html>"))
        self.resultado.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.bsuma.setText(_translate("Dialog", "SUMA"))
        self.bresta.setText(_translate("Dialog", "RESTA"))
        self.bmultiplicar.setText(_translate("Dialog", "MULTIPLICAR"))
        self.bcociente.setText(_translate("Dialog", "COCIENTE"))
        self.btangente.setText(_translate("Dialog", "TANGENTE"))
        self.bcoseno.setText(_translate("Dialog", "COSENO"))
        self.bresiduo.setText(_translate("Dialog", "RESIDUO"))
        self.bseno.setText(_translate("Dialog", "SENO"))
        self.bcosecante.setText(_translate("Dialog", "COSECANTE"))
        self.bcotangente.setText(_translate("Dialog", "COTANG"))
        self.bsecante.setText(_translate("Dialog", "SECANTE"))

    def suma(self):
        valora = int(self.valor1.toPlainText())
        valorb = int(self.valor2.toPlainText())
        operacion = str(valora + valorb)
        self.resultado.setText(operacion)
    def resta(self):
        valora = int(self.valor1.toPlainText())
        valorb = int(self.valor2.toPlainText())
        operacion = str(valora - valorb)
        self.resultado.setText(operacion)
    def multiplicacion(self):
        valora = int(self.valor1.toPlainText())
        valorb = int(self.valor2.toPlainText())
        operacion = str(valora * valorb)
        self.resultado.setText(operacion)
    def cociente(self):
        valora = int(self.valor1.toPlainText())
        valorb = int(self.valor2.toPlainText())
        operacion = str(valora // valorb)
        self.resultado.setText(operacion)
    def residuo(self):
        valora = int(self.valor1.toPlainText())
        valorb = int(self.valor2.toPlainText())
        operacion = str(valora % valorb)
        self.resultado.setText(operacion)
    def seno(self):
        #valora = int(self.valor1.toPlainText())
        valorb = float(self.valor2.toPlainText())
        seno = str(math.sin(valorb))
        self.resultado.setText(seno)
    def coseno(self):
        valorb = float(self.valor2.toPlainText())
        seno = str(math.cos(valorb))
        self.resultado.setText(seno)
    def tangente(self):
        valorb = float(self.valor2.toPlainText())
        seno = str(math.tan(valorb))
        self.resultado.setText(seno)
    def cotangente(self):
        valorb = float(self.valor2.toPlainText())
        tangente = math.tan(valorb)
        tan = str(1/tangente)
        self.resultado.setText(tan)
    def secante(self):
        valorb = float(self.valor2.toPlainText())
        coseno = math.cos(valorb)
        secante = str(1 / coseno)
        self.resultado.setText(secante)
    def cosecante(self):
        valorb = float(self.valor2.toPlainText())
        seno = math.sin(valorb)
        cosecante = str(1 /seno)
        self.resultado.setText(cosecante)

        



        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    ui.bsuma.clicked.connect(ui.suma)
    ui.bresta.clicked.connect(ui.resta)
    ui.bmultiplicar.clicked.connect(ui.multiplicacion)
    ui.bresiduo.clicked.connect(ui.residuo)
    ui.bcociente.clicked.connect(ui.cociente)
    ui.bseno.clicked.connect(ui.seno)
    ui.bcoseno.clicked.connect(ui.coseno)
    ui.btangente.clicked.connect(ui.tangente)
    ui.bcotangente.clicked.connect(ui.cotangente)
    ui.bsecante.clicked.connect(ui.secante)
    ui.bcosecante.clicked.connect(ui.cosecante)
    Dialog.show()
    sys.exit(app.exec_())
