# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'i2c.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(558, 348)
        Dialog.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(200, 20, 161, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 91, 21))
        self.label_2.setObjectName("label_2")
        self.lectura = QtWidgets.QTextEdit(Dialog)
        self.lectura.setGeometry(QtCore.QRect(180, 110, 121, 31))
        self.lectura.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lectura.setObjectName("lectura")
        self.tiempo = QtWidgets.QTextEdit(Dialog)
        self.tiempo.setGeometry(QtCore.QRect(180, 170, 121, 31))
        self.tiempo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.tiempo.setObjectName("tiempo")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 170, 91, 21))
        self.label_3.setObjectName("label_3")
        self.boton_ejecutar = QtWidgets.QPushButton(Dialog)
        self.boton_ejecutar.setGeometry(QtCore.QRect(380, 260, 80, 25))
        self.boton_ejecutar.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.boton_ejecutar.setObjectName("boton_ejecutar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700;\">SENSOR TCS3472</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700;\">lectura</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700;\">tiempo</span></p></body></html>"))
        self.boton_ejecutar.setText(_translate("Dialog", "Ejecutar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
