# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'punto2_leds_y_slider.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from gpiozero import LED
from time import sleep
from PyQt5 import QtCore, QtGui, QtWidgets
import RPi.GPIO as GPIO

ledRojo = LED(17)
ledAzul = LED(27)
GPIO.setmode(GPIO.BCM)
slidera = 12
sliderb = 13
GPIO.setup(slidera, GPIO.OUT)
GPIO.setup(sliderb, GPIO.OUT)
pwm = GPIO.PWM(slidera, 50)
pwm2 = GPIO.PWM(sliderb, 50)
pwm.start(0)
pwm2.start(0)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(701, 470)
        Dialog.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(290, 50, 161, 51))
        self.label.setObjectName("label")
        self.botonLedRojo = QtWidgets.QPushButton(Dialog)
        self.botonLedRojo.setGeometry(QtCore.QRect(310, 150, 131, 31))
        self.botonLedRojo.setStyleSheet("colo: rgb(255, 0, 0);")
        self.botonLedRojo.setObjectName("botonLedRojo")
        #self.botonLedRojo.set
        self.BotonLedAzul = QtWidgets.QPushButton(Dialog)
        self.BotonLedAzul.setGeometry(QtCore.QRect(310, 200, 131, 31))
        self.BotonLedAzul.setStyleSheet("\nbackground-color: rgb(0, 0, 255);")
        self.BotonLedAzul.setObjectName("BotonLedAzul")
        self.slider1 = QtWidgets.QSlider(Dialog)
        self.slider1.setGeometry(QtCore.QRect(300, 270, 160, 22))
        self.slider1.setStyleSheet("color: rgb(170, 170, 255);")
        self.slider1.setOrientation(QtCore.Qt.Horizontal)
        self.slider1.setObjectName("slider1")
        self.slider2 = QtWidgets.QSlider(Dialog)
        self.slider2.setGeometry(QtCore.QRect(300, 320, 160, 22))
        self.slider2.setStyleSheet("color: rgb(170, 170, 255);")
        self.slider2.setOrientation(QtCore.Qt.Horizontal)
        self.slider2.setObjectName("slider2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">LEDS</span></p></body></html>"))
        self.botonLedRojo.setText(_translate("Dialog", "LED"))
        self.BotonLedAzul.setText(_translate("Dialog", "LED"))
        self.slider1.setStyleSheet("color: rgb(170, 170, 255);")
        self.slider1.setStyleSheet("color: rgb(170, 170, 255);")

    def botonrojo (self):
        estado  = ledRojo.is_lit
        self.slider1.setStyleSheet("color: rgb(170, 170, 255);")
        if estado:
            ledRojo.off()
        else:
            ledRojo.on()
            #self.slider1.setStyleSheet("color: rgb(170, 170, 255);")
    def botonazul (self):
        estado  = ledAzul.is_lit
        if estado:
            ledAzul.off()
        else:
            ledAzul.on()
    def primerslider (self):
        valor_slider = self.slider1.value()
        m = 0.10
        b = 2.4
        posicion = (valor_slider * m) + b
        pwm.ChangeDutyCycle(posicion)



    def segundoslider (self):
        valorsegundoslider = self.slider2.value()
        m = 0.10
        b = 2.4
        posicion = (valorsegundoslider * m) + b 
        pwm2.ChangeDutyCycle(posicion)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    ui.botonLedRojo.clicked.connect(ui.botonrojo)
    ui.BotonLedAzul.clicked.connect(ui.botonazul)
    ui.slider1.sliderMoved.connect(ui.primerslider)
    ui.slider2.sliderMoved.connect(ui.segundoslider)
    Dialog.show()
    sys.exit(app.exec_())
